language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
script:
  - echo "No tests"
after_success:
  - git clone git://github.com/iblancasa/GitHubRankingsSpain.git generated
  - make multi
  - make spain-region
  - git config --global user.email "iblancasa@gmail.com"
  - git config --global user.name "Israel Blancas"
  - cd generated
  - git remote
  - git add *
  - git commit -m "New rankings were generated"
  - git push "https://iblancasa:${ACCESS}@github.com/iblancasa/GitHubRankingsSpain.git" master > /dev/null 2>&1
